<div class="footer-top-showroom">
    <?php echo $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('footer_top_showroom')
        ->toHtml();
    ?>
</div>

<div class="footer-top-banner">
    <?php echo $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('footer_top_banner')
        ->toHtml();
    ?>
</div>

<div class="footer-top-info">
    <?php echo $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('footer_top_info')
        ->toHtml();
    ?>
</div>